version: '3'
services:
  kitabikin-admin-local:
    build:
      context: .
      dockerfile: .docker/local.dockerfile
    image: rendiriz/kitabikin-admin:local
    container_name: 'kitabikin-admin-local'
    ports:
      - '1801:80'
    restart: always
