version: '3'
services:
  kitabikin-admin-main:
    build:
      context: .
      dockerfile: .docker/main.dockerfile
    image: kitabikincom/kitabikin-admin:main
    container_name: 'kitabikin-admin-main'
    ports:
      - '18121:80'
    restart: always
